title: Haoran Xu
description: Mathematics undergraduate currently studying extremal graph theory.
url: "https://xuhr-42.github.io"
baseurl: ""
lang: en
timezone: Asia/Shanghai
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
exclude:
  - README.md
  - LICENSE
